apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
  labels:
    app: vikunja
data:
  config.yml: |
    log:
      level: {{ default .Values.logLevel .Values.config.logLevel | quote }}
    service:
      publicurl: {{ default (printf "https://%s" .Values.ingress.host) .Values.config.publicUrl | quote }}
    auth:
      local:
        enabled: true
      openid:
        enabled: {{ if .Values.openid.enabled }}true{{ else }}false{{ end }}
        redirecturl: {{ printf "https://%s/auth/openid/" .Values.ingress.host | quote }}
        providers:
        {{- range .Values.openid.providers }}
          - name: {{ .name | quote }}
            authurl: {{ .authurl | quote }}
            logouturl: {{ .logouturl | quote }}
            clientid: {{ .clientid | quote }}
            {{- if .clientsecret }}
            clientsecret: {{ .clientsecret | quote }}
            {{- end }}
            scopes:
            {{- $scopes := .scopes | default (splitList " " (.scope | default "")) -}}
            {{- range $scopes }}
              - {{ . | quote }}
            {{- end }}
        {{- end }}