apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
  labels:
    app: vikunja
data:
  config.yml: |
    log:
      level: {{ default .Values.logLevel .Values.config.logLevel }}
    service:
      publicurl: {{ default (printf "https://%s" .Values.ingress.host) .Values.config.publicUrl }}
    auth:
      local:
        enabled: true
      openid:
        enabled: {{ if .Values.openid.enabled }}true{{ else }}false{{ end }}
        redirecturl: {{ printf "https://%s/auth/openid/" .Values.ingress.host }}
        providers:
        {{- range .Values.openid.providers }}
          - name: {{ .name }}
            authurl: {{ .authurl }}
            logouturl: {{ .logouturl }}
            clientid: {{ .clientid }}
            {{- if .clientsecret }}
            clientsecret: {{ .clientsecret }}
            {{- end }}
            scopes: {{ $scopes := .scopes | default (splitList " " (.scope | default "")) }}{{ range $i, $s := $scopes }}{{ if $i }} {{ end }}{{ $s }}{{ end }}
        {{- end }}