apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vikunja.fullname" . }}-config
data:
  config.yml: |
    service:
      jwtttl: 3600
    database:
      type: postgres
      host: {{ .Values.postgres.host }}
      user: {{ .Values.postgres.user }}
      database: {{ .Values.postgres.database }}
    auth:
      openid:
        enabled: {{ .Values.openid.enabled }}
        providers:
          - name: keycloak
            authurl: {{ .Values.openid.issuer }}/protocol/openid-connect/auth
            tokenurl: {{ .Values.openid.issuer }}/protocol/openid-connect/token
            clientid: {{ .Values.openid.clientId }}
            clientsecret: {{ if and .Values.openid.confidentialClient .Values.openid.secretName }}"${VIKUNJA_AUTH_OPENID_CLIENTSECRET}"{{ else }}""{{ end }}
