apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vikunja.fullname" . }}-config
data:
  config.yml: |
    service:
      jwtttl: 3600
    database:
      type: postgres
      host: {{ .Values.postgres.host }}
      user: {{ .Values.postgres.user }}
      database: {{ .Values.postgres.database }}
    auth:
      openid:
        enabled: {{ .Values.keycloak.enabled }}
        providers:
          - name: keycloak
            authurl: {{ .Values.keycloak.issuer }}/protocol/openid-connect/auth
            tokenurl: {{ .Values.keycloak.issuer }}/protocol/openid-connect/token
            clientid: vikunja-frontend
            clientsecret: ""
