apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      serviceAccountName: vikunja
      containers:
        - name: api
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VIKUNJA_DATABASE_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: VIKUNJA_DATABASE_USER
              value: {{ .Values.postgres.user | quote }}
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default "vikunja-db" .Values.postgres.secretName | quote }}
                  key: {{ default "password" .Values.postgres.passwordKey | quote }}
            - name: VIKUNJA_DATABASE_DATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: VIKUNJA_CONFIG
              value: "/etc/vikunja/config.yml"
          ports:
            - name: http
              containerPort: 3456
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: vikunja-config
              mountPath: /etc/vikunja
              readOnly: true
        - name: frontend
          image: {{ .Values.frontend.image | quote }}
          ports:
            - name: web
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
            failureThreshold: 3
      volumes:
        - name: vikunja-config
          configMap:
            name: vikunja-config
