apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      serviceAccountName: vikunja
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Database host
            - name: VIKUNJA_DATABASE_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: VIKUNJA_DATABASE_USER
              value: {{ .Values.postgres.user | quote }}
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName | default "vikunja" }}
                  key: {{ .Values.postgres.passwordKey | default "DB_PASSWORD" }}
            - name: VIKUNJA_DATABASE_DATABASE
              value: {{ .Values.postgres.database | quote }}
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "https://{{ .Values.ingress.host }}"
            {{- if .Values.openid.enabled }}
            - name: VIKUNJA_AUTH_OPENID_ENABLED
              value: "true"
            - name: VIKUNJA_AUTH_OPENID_ISSUER
              value: {{ .Values.openid.issuer | quote }}
            - name: VIKUNJA_AUTH_OPENID_CLIENTID
              value: {{ .Values.openid.clientId | quote }}
            - name: VIKUNJA_AUTH_OPENID_REDIRECTURL
              value: {{ .Values.openid.redirectURL | quote }}
            - name: VIKUNJA_AUTH_OPENID_SCOPE
              value: {{ .Values.openid.scopes | quote }}
            {{- if and .Values.openid.confidentialClient .Values.openid.secretName }}
            - name: VIKUNJA_AUTH_OPENID_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openid.secretName }}
                  key: CLIENT_SECRET
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 3456
              name: http
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.cloudsql.enabled }}
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.37.0
          command:
            - /cloud_sql_proxy
            - -instances={{ required "cloudsql.instanceConnectionName is required when cloudsql.enabled=true" .Values.cloudsql.instanceConnectionName }}=tcp:5432
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
        {{- end }}
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80
              name: web
          livenessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 10
            periodSeconds: 10
