{{- if .Values.networkPolicy.enabled }}
# NetworkPolicy for Vikunja
# Ingress: allow cluster-internal any source to service ports 80 (frontend) & 3456 (API)
# Egress: allow DNS + Postgres (5432) + HTTPS (443) for OIDC discovery
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  podSelector:
    matchLabels:
      app: vikunja
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 3456
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 443
{{- end }}
