apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vikunja.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "vikunja.name" . }}
