apiVersion: v1
kind: Service
metadata:
  name: {{ include "vikunja.fullname" . }}
  labels:
    app: {{ include "vikunja.name" . }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: {{ include "vikunja.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: http
  type: {{ .Values.service.type }}
