image:
  repository: quay.io/keycloak/keycloak
  tag: 24.0.1

database:
  host: 0.0.0.0            # Overridden via --set database.host=<cloudsql_public_ip>
  name: keycloak
  user: keycloak
  parameters: "?sslmode=require"  # Additional JDBC parameters (prefixed with '?' for proper URL formatting)

cloudsql:
  enabled: false            # Direct mode default; enable for proxy approach
  instanceConnectionName: "" # Only used if enabled
  image: gcr.io/cloudsql-docker/gce-proxy:1.37.0
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

serviceAccount:
  create: true
  name: ""  # If empty, will default to chart fullname
  annotations: {}
  workloadIdentity:
    enabled: false
    gsaEmail: "" # e.g. vikunja-workloads@sixth-bonbon-475003-q2.iam.gserviceaccount.com

ingress:
  enabled: false
  host: keycloak.example.com
  className: ""
  annotations: {}
  tls: []

# Explicit hostname when using shared platform ingress (ingress.enabled=false)
hostnameOverride: "keycloak.misskecupbung.xyz"

# Realm bootstrap configuration (executed via a Helm post-install/upgrade Job when enabled)
realm:
  enabled: false # disabled pending simplified bootstrap job fix
  name: vikunja
  clients: []

# Post-install Job toggle (realm.enabled controls creation; this is a secondary master switch if desired)
postInstall:
  enabled: true
