image:
  repository: quay.io/keycloak/keycloak
  tag: 24.0.1

database:
  host: 0.0.0.0            # Overridden via --set database.host=<cloudsql_public_ip>
  name: vikunja
  user: vikunja
  parameters: "sslmode=require"  # Additional JDBC parameters

cloudsql:
  enabled: false            # Direct mode default; enable for proxy approach
  instanceConnectionName: "" # Only used if enabled
  image: gcr.io/cloudsql-docker/gce-proxy:1.37.0
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

ingress:
  enabled: false
  host: keycloak.example.com
  className: ""
  annotations: {}
  tls: []

# Realm bootstrap configuration (executed via a Helm post-install/upgrade Job when enabled)
realm:
  enabled: false
  name: vikunja
  clients: []
  # Example:
  # clients:
  #   - clientId: vikunja-web
  #     publicClient: true
  #     redirectUris:
  #       - "https://vikunja.example.com/*"

# Post-install Job toggle (realm.enabled controls creation; this is a secondary master switch if desired)
postInstall:
  enabled: true
