image:
  repository: quay.io/keycloak/keycloak
  tag: 24.0.1

database:
  host: 0.0.0.0
  name: keycloak
  user: keycloak
  parameters: "?sslmode=disable" 

cloudsql:
  enabled: false
  instanceConnectionName: "" # Only used if enabled
  image: gcr.io/cloudsql-docker/gce-proxy:1.37.0
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

serviceAccount:
  create: true
  name: "" 
  annotations: {}
  workloadIdentity:
    enabled: false
    gsaEmail: ""

ingress:
  enabled: false
  host: keycloak.example.com
  className: ""
  annotations: {}
  tls: []

hostnameOverride: "keycloak.misskecupbung.xyz"

realm:
  enabled: false
  name: vikunja
  clients: []

postInstall:
  enabled: true
