image:
  repository: quay.io/keycloak/keycloak
  tag: 24.0.1

database:
  host: 0.0.0.0
  name: keycloak
  user: keycloak
  parameters: "?sslmode=disable"

cloudsql:
  enabled: false
  instanceConnectionName: ""
  image: gcr.io/cloudsql-docker/gce-proxy:1.37.0
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

ingress:
  enabled: true
  host: keycloak.local
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
  tls: []

hostnameOverride: "keycloak.misskecupbung.xyz"

realm:
  enabled: false
  name: vikunja
  clients:
    - clientId: vikunja-web
      publicClient: true
      redirectUris:
        - "https://vikunja.misskecupbung.xyz/*"

postInstall:
  enabled: true
