database:
  host: vikunja-db.public-ip-or-dns   # Replaced in CI pipeline with gcloud-derived Cloud SQL public IP
  name: keycloak                       # Dedicated Keycloak DB (managed via Terraform)
  user: keycloak                       # Dedicated Keycloak DB user
  parameters: "?sslmode=require"

ingress:
  enabled: true
  className: "gce"
  host: keycloak.local
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
  tls: []

realm:
  enabled: false
  name: vikunja
  clients:
    - clientId: vikunja-web
      publicClient: true
      redirectUris:
        - "https://vikunja.local/*"