keycloak:
  auth:
    adminUser: admin
    adminPassword: ChangeMeAdmin!
  replicaCount: 2
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  postgresql:
    enabled: true
    auth:
      username: keycloak
      password: ChangeMeKC!
      database: keycloak
